#!/usr/bin/env python3
"""
modemserver binary patcher
Translates Chinese UI strings to English in the embedded Vite/React bundle.
Usage: python3 patch_binary.py
Output: modemserver_en  (patched binary, same permissions)
"""

import re
import os
import stat
import sys

# --- Translation table ---
# Rules: English must fit in same byte count as Chinese (UTF-8).
#        Shorter strings are right-padded with spaces.
#        Trailing spaces in HTML are collapsed; in JS logic strings avoid padding.
TRANSLATIONS = {
    # ── Page title ──────────────────────────────────────────────────────────
    "5G联通未来-马上有房出品": "5G Modem Manager",

    # ── Top-level navigation ────────────────────────────────────────────────
    "蜂窝网络":   "Cellular",
    "5G模块管理": "5G Module Mgr",
    "模块管理":   "Module Mgmt",
    "AT工具":     "AT Tool",
    "短消息管理": "SMS Manager",
    "基站频段管理":"Cell Band Ctrl",
    "网络流量统计":"Traffic Stats",
    "详细网络信息":"Network Details",
    "模块配置与监控":"Module Config",
    "实时监控":   "Live Monitor",
    "串口设备AT指令发送与响应管理": "Serial AT Command Console",
    "查看、发送和管理移动设备短消息": "View/Send/Manage SMS Messages",
    "锁定/解锁基站与频段，优化网络连接": "Lock/Unlock cells & bands",
    "配置与监控5G模块的运行状态与参数": "Configure & Monitor 5G Module",
    "管理5G模块的硬件参数与网络设置": "Manage 5G Module HW & Network",
    "实时监测模块信号状态与网络参数": "Real-time Signal & Network Monitor",
    "查看和发送短消息内容": "View and Send SMS",
    "实时显示5G模块网络状态": "Live 5G Module Network Status",
    "串口检测失败，请重试": "Serial detect failed, retry",

    # ── Section titles ───────────────────────────────────────────────────────
    "小区信息":    "Cell Info",
    "信号网络":    "Signal & Net",
    "信号参数":    "Sig Params",
    "模块设置":    "Mod Config",
    "硬件设置":    "HW Settings",
    "网络配置":    "Net Config",
    "短信转发":    "SMS Forward",
    "系统日志":    "System Log",
    "命令控制台":  "AT Console",
    "通用命令":    "Common Cmds",
    "根级通用命令集": "Root Commands",
    "基站与频段控制": "Cell & Band Ctrl",
    "基站管理":    "Cell Mgmt",
    "频段管理":    "Band Mgmt",
    "模块型号":    "Module Model",
    "设备注册授权": "Device Reg.",
    "申请状态查询": "Application Status",
    "密钥申请":    "Key Request",
    "网络模式":    "Network Mode",
    "5G接入模式选择": "5G Access Mode",
    "SIM卡切换":   "SIM Switch",
    "SIM卡信息":   "SIM Card Info",
    "SMS短消息管理": "SMS Manager",
    "AT命令管理工具": "AT Command Tool",
    "自动串口管理": "Auto Serial Mgmt",
    "DNS地址设置": "DNS Settings",
    "在此设置IMEI": "Set IMEI Here",
    "小区信息-HFREQINFO": "Cell Info-HFREQINFO",
    "小区信息-MONSC":     "Cell Info-MONSC",
    "Quectel厂商命令集（高通平台）": "Quectel Commands (Qualcomm)",
    "Fibocom厂商命令集（高通平台）": "Fibocom Commands (Qualcomm)",
    "Foxconn厂商命令集（高通平台）": "Foxconn Commands (Qualcomm)",
    "Meig厂商命令集（高通平台）":    "Meig Commands (Qualcomm)",

    # ── Field labels ─────────────────────────────────────────────────────────
    "移动国家码":  "MCC",
    "移动网络码":  "MNC",
    "物理小区ID":  "PCI",
    "跟踪区码":    "TAC",
    "下行带宽":    "DL BW",
    "上行带宽":    "UL BW",
    "频段指示":    "Band",
    "子载波间隔":  "SCS",
    "发射功率":    "TX Power",
    "位置区码":    "LAC",
    "路由区码":    "RAC",
    "物理信道":    "Phy Chan",
    "扩频因子":    "SF",
    "语音编码":    "Codec",
    "通信模式":    "Comm Mode",
    "双工模式":    "Duplex",
    "是否TDD":     "TDD",
    "能量/码片":   "Ec/Io",
    "主扰码":      "PSC",
    "小区ID":      "Cell ID",
    "参考信号接收功率": "RSRP",
    "参考信号接收质量": "RSRQ",
    "接收信号强度指示": "RSSI",
    "信号与干扰加噪声比": "SINR",
    "绝对无线频率信道号": "ARFCN",
    "E-UTRA绝对无线频率信道号": "EARFCN",
    "UTRA绝对无线频率信道号":   "UARFCN",
    "接收信号码功率": "RSCP",
    "信道质量指示": "CQI",
    "信号强度等级": "Signal Level",
    "信号强度":    "Signal Str",
    "固件版本":    "FW Version",
    "硬件速率":    "HW Speed",
    "拨号模式":    "Dial Mode",
    "串口设备":    "Serial Dev",
    "监控地址":    "Monitor Addr",
    "自动获取":    "Auto",
    "接入点名称":  "APN",
    "自动APN":     "Auto APN",
    "手动DNS":     "Man. DNS",
    "是否开启IPV6":  "Enable IPv6",
    "首选DNS服务器": "Primary DNS",
    "备用DNS服务器": "Secondary DNS",
    "是否开启短信转发": "Enable SMS Fwd",
    "手机号码":    "Phone Number",
    "获取手机号码": "Get Phone No.",
    "获取运营商":  "Get Operator",
    "获取SIM卡信息": "Get SIM Info",
    "获取SIM状态": "Get SIM Status",
    "获取ICCID":   "Get ICCID",
    "获取IMSI":    "Get IMSI",
    "获取固件版本": "Get FW Version",
    "获取电压":    "Get Voltage",
    "获取温度":    "Get Temp",
    "SIM状态":     "SIM Stat",
    "SIM卡信息": "SIM Info",
    "运营商":      "Operator",
    "当前运营商":  "Current Oper.",
    "厂商":        "Vendor",
    "平台":        "Platf",
    "频段":        "Band",
    "时隙":        "Slot",
    "电压":        "Volt",
    "温度":        "Temp",
    "速率":        "Speed",
    "状态":        "Status",
    "信号":        "Signal",
    "短信":        "SMS",

    # ── Connection/status strings ────────────────────────────────────────────
    "已连接":      "Connected",
    "未连接":      "Offline",
    "无数据":      "No Data",
    "未授权":      "Unauth.",
    "已读":        "Read",
    "未读":        "Unread",
    "锁定":        "Lock",
    "解锁":        "Unlock",
    "已锁基站":    "Cell Locked",
    "已锁频段":    "Band Locked",
    "连接类型":    "Conn Type",
    "接入模式":    "Access Mode",
    "纯5G网络，低延迟高带宽，需要5G核心网支持": "Pure 5G, low latency, requires 5G core",
    "5G与4G混合组网，依赖4G核心网，兼容性更好": "5G+4G hybrid, uses 4G core, better compat.",
    "同时支持SA和NSA，根据网络环境自动切换": "SA+NSA auto-switch based on network",
    "根据信号质量和网络负载自动选择最优接入模式": "Auto-select best mode by signal & load",
    "选择合适的5G接入模式以优化网络性能和兼容性": "Choose 5G access mode for best performance",
    "SA (独立组网)":  "SA (Standalone)",
    "NSA (非独立组网)": "NSA (Non-Standalone)",
    "SA+NSA (混合模式)": "SA+NSA (Mixed)",
    "SA+NSA混合模式":  "SA+NSA Mixed",
    "SA+NSA模式":      "SA+NSA Mode",
    "NSA模式":         "NSA Mode",
    "SA模式":          "SA Mode",
    "独立组网":        "Standalone",
    "非独立组网":      "Non-Standalone",
    "混合模式":        "Mixed Mode",
    "智能选择":        "Smart Select",
    "自动模式":        "Auto Mode",
    "未知模式":        "Unknown Mode",
    "当前使用":        "In Use",

    # ── Operators ────────────────────────────────────────────────────────────
    "中国移动": "China Mobile",
    "中国联通": "China Unicom",
    "中国电信": "CN Telecom",
    "中国广电": "CN Broadnet",
    "广电":     "CRTC",
    "钉钉":     "DingTk",
    "飞书":     "Feishu",
    "企业微信": "WeCom",

    # ── Button labels ────────────────────────────────────────────────────────
    "发送":        "Send",
    "取消":        "Cancel",
    "确定":        "OK",
    "复制":        "Copy",
    "全选":        "All",
    "跳至":        "Go to",
    "上一页":      "Prev",
    "下一页":      "Next",
    "向前 5 页":   "Back 5p",
    "向后 5 页":   "Fwd 5p",
    "向前 3 页":   "Back 3p",
    "向后 3 页":   "Fwd 3p",
    "条/页":       "per pg",
    "刷新列表":    "Refresh",
    "锁定选中":    "Lock Sel.",
    "解锁选中":    "Unlock Sel.",
    "全部锁定":    "Lock All",
    "全部解锁":    "Unlock All",
    "删除选中":    "Delete Sel.",
    "发送新消息":  "New SMS",
    "发送消息":    "Send Msg",
    "收件箱":      "Inbox",
    "发件箱":      "Outbox",
    "保存历史":    "Save Hist",
    "保存设置":    "Save Sett.",
    "确认保存":    "Confirm Save",
    "清空日志":    "Clear Log",
    "导出日志":    "Export Log",
    "重连失败":    "Reconnect Failed",
    "尝试重连":    "Reconnecting",
    "新申请":      "New App",
    "提交申请":    "Submit",
    "查询状态":    "Check Status",
    "重新查询":    "Re-query",
    "完成注册授权": "Complete Reg.",
    "选择模块":    "Select Mod",
    "隐藏详情":    "Hide Details",
    "显示详情":    "Show Details",
    "收起":        "Less",
    "更多":        "More",
    "实时发送":    "Live TX",
    "实时接收":    "Live RX",
    "保存失败":    "Save Failed",
    "保存成功":    "Saved",
    "日志已清空":  "Log Cleared",
    "历史记录已保存": "History Saved",
    "硬件设置已更新": "HW Settings Updated",
    "网络设置已更新": "Net Settings Updated",
    "实时通信已就绪": "Real-time Ready",

    # ── Messages & notifications ─────────────────────────────────────────────
    "未知":        "N/A",
    "良好":        "Good",
    "一般":        "Fair",
    "较差":        "Poor",
    "回复":        "Reply",
    "转发":        "Fwd",
    "信息":        "Info",
    "响应":        "Resp",
    "清空":        "Clear",
    "您有新短信":  "New SMS",
    "退出提醒":    "Exit Prompt",
    "权限不足":    "No Access",
    "登录失败":    "Login Failed",
    "账户登录":    "Acct Login",
    "登录系统":    "Sign In",
    "联系邮箱":    "Email",
    "登录成功，正在进入系统...": "Login successful, loading...",
    "请输入您的账号信息访问系统": "Enter credentials to access system",
    "请输入用户名": "Enter username",
    "请输入密码":   "Enter password",
    "用户名至少3个字符": "Username min 3 chars",
    "密码至少6个字符":   "Password min 6 chars",
    " 登录中... ": " Loading... ",
    " 处理中... ": " Working... ",
    " 提交中... ": " Submit... ",
    " 查询中... ": " Querying... ",
    " 是否确认执行此操作？ ": " Confirm this action? ",
    " 是否确认退出系统？ ":   " Confirm exit? ",
    " 我已确认所提供信息真实有效 ": " I confirm the provided info is valid ",
    " 同意设备授权协议 ": " Agree to auth ",

    # Status messages
    "连接发生错误": "Connection error",
    "发送消息失败": "Send msg failed",
    "发送失败":     "Send failed",
    "操作失败，请重试": "Operation failed, retry",
    "刷新失败，请重试": "Refresh failed, retry",
    "模块切换失败，请重试": "Module switch failed",
    "模式切换失败，请重试": "Mode switch failed",
    "设备切换失败，请重试": "Device switch failed",
    "串口检测失败，请重试": "Serial detect failed",
    "锁定失败，请重试": "Lock failed, retry",
    "解锁失败，请重试": "Unlock failed, retry",
    "设置保存成功": "Settings saved",
    "消息发送成功": "Message sent",
    "日志导出成功": "Log exported",
    "密钥已复制到剪贴板": "Key copied to clipboard",
    "复制失败，请手动复制": "Copy failed, copy manually",
    "设备注册授权成功！": "Device registered!",
    "已删除选中的消息": "Msgs deleted",
    "已清空历史记录": "History cleared",
    "已锁定所有频段": "All bands locked",
    "已解锁所有频段": "All bands unlocked",
    "基站列表已刷新": "Cell list refreshed",
    "频段列表已刷新": "Band list refreshed",
    "没有收到任何消息": "No messages received",
    "没有发送任何消息": "No messages sent",
    "没有找到日志记录": "No log records found",
    "总发送":       "TX Total",
    "总接收":       "RX Total",
    "信号强度:":    "Signal:",
    "模块状态: ":   "Module: ",
    "信号状态: ":   "Signal: ",
    "当前设备: ":   "Device: ",
    "运营商:":      "Operator:",
    "网络类型:":    "Net Type:",
    "频率范围:":    "Freq Range:",
    "发件人:":      "From:",
    "发送: ":       "TX: ",
    "响应: ":       "RX: ",
    " 条结果":      " results",
    "时间:":        "Time:",
    "距离:":        "Dist:",
    "输入:":        "Input:",
    "IP 地址：":    "IP Addr:",

    # Error / warning strings
    "WebSocket未连接，请稍后重试": "WebSocket not connected, wait",
    "WebSocket连接已关闭": "WebSocket closed",
    "WebSocket连接超时": "WebSocket timeout",
    "WebSocket连接成功": "WebSocket connected",
    "WebSocket错误":    "WebSocket error",
    "WebSocket错误:":   "WebSocket error:",
    "网络错误，请稍后重试": "Network error, retry later",
    "初始化WebSocket失败:": "WS init failed:",
    "发送WebSocket消息失败:": "WS send failed:",
    "解析WebSocket消息失败:": "WS parse failed:",
    "已取消请求":    "Cancelled",
    "重连失败":      "Reconn Fail",
    "路由守卫检查登录状态失败:": "Auth guard check failed:",
    "已达到最大重连次数，请检查网络或重新登录": "Max retries reached, check network",
    "未匹配到配置": "No config matched",
    "未检测到设备": "No device detected",
    "未找到基站信息，请刷新重试": "No cell info, refresh",
    "未找到频段信息，请刷新重试": "No band info, refresh",
    "无效的AT响应格式": "Invalid AT response",
    "无效的参数：data必须是数组，targetCommand必须是字符串": "Invalid params: data must be array, targetCommand must be string",
    "初始化模块数据不是数组，使用默认数据": "Module data not array, using default",
    "外部传入的modules不是数组，忽略更新": "External modules not array, skipping",
    "setModules需传入数组": "setModules requires array",
    "外部模块数据已同步到内部:": "External module data synced:",
    "内部模块数据已同步到外部:": "Internal module data synced:",
    "初始化失败:":   "Init failed:",
    "发送消息失败:": "Send failed:",
    "登录请求失败:": "Login failed:",
    "获取当前模块失败:": "Get module failed:",
    "获取当前设备失败:": "Get device failed:",
    "路由守卫检查登录状态失败:": "Auth guard failed:",
    "组件初始化数据:": "Component init data:",
    "同步外部选中值:": "Sync external value:",
    "[QENG Parser] 输入数据:": "[QENG Parser] Input:",
    "[QENG Parser] 检测到 5G SA 模式": "[QENG Parser] 5G SA mode detected",
    "[QENG Parser] 5G SA 匹配成功": "[QENG Parser] 5G SA match OK",
    "[QENG Parser] 5G SA 匹配失败": "[QENG Parser] 5G SA match FAIL",
    "EventAdded 事件缺少关键字段（Device/Product），忽略该模块": "EventAdded missing key fields, skip",
    "EventAdded 事件无法获取模块ID，忽略该模块": "EventAdded: cannot get module ID",
    "EventRemoved 事件无法获取模块ID，忽略该操作": "EventRemoved: cannot get module ID",
    "初始化模块数据不是数组，使用默认数据": "Module init data not array, using default",

    # No-data states
    "暂无模块数据":      "No module data",
    "暂无模块数据，请先添加模块": "No modules, please add one",
    "暂无模块数据，请添加模块后使用": "No modules available",
    "暂无模块数据，请稍后刷新": "No modules, refresh later",
    "暂无模块数据，请刷新重试": "No modules, refresh",
    "暂无模块数据，无法切换": "No modules to switch",
    "暂无模块数据，无法删除": "No modules to delete",
    "暂无模块数据，无法回复": "No modules to reply",
    "暂无模块数据，无法发送": "No modules to send",
    "暂无设备数据，请稍后刷新": "No devices, refresh later",
    "暂无设备数据，请先添加设备": "No devices, add one first",
    "暂无设备数据，无法切换": "No devices to switch",
    "暂无设备数据，无法保存": "No devices to save",
    "暂无设备数据，无法清空": "No devices to clear",
    "暂无设备数据，无法导出": "No devices to export",
    "选中的模块不存在": "Module not found",
    "选中的设备不存在": "Device not found",
    "未选择模块":      "No module sel.",
    "未选择设备":      "No device sel.",
    "设备未在线，无法保存设置": "Device offline, cannot save",
    "模块未连接，无法删除消息": "Module disconnected, cannot delete",
    "模块未连接，无法回复消息": "Module disconnected, cannot reply",
    "模块未连接，无法转发消息": "Module disconnected, cannot forward",
    "模块未连接，无法发送消息": "Module disconnected, cannot send",
    "无日志数据可导出": "No log data to export",

    # Modem management
    "密钥申请通常在1-3个工作日内完成审核，审核通过后将通过邮件发送": "Key review takes 1-3 business days, result sent by email",
    "管理员正在审核您的申请，预计1-3个工作日完成": "Admin reviewing, est. 1-3 business days",
    "您的密钥申请已提交成功，正在等待管理员审核": "Application submitted, awaiting review",
    "您的密钥申请已通过审核，授权密钥已生成": "Application approved, key generated",
    "您的密钥申请未通过审核，请根据原因修改后重新申请": "Application rejected, revise and resubmit",
    "设备编号未在系统中注册，请先完成设备注册后再申请密钥": "Device not registered, register first",
    "密钥申请已提交，我们将尽快审核！": "Application submitted, we'll review soon!",
    "密钥只能包含字母、数字和特殊字符(+/=)": "Key: letters, digits, and +/= only",
    "密钥必须为64位字符串": "Key must be 64-char string",
    "密钥通常为64位字符串，用于设备身份验证": "Key is typically 64 chars for device auth",
    "* 完整密钥已发送至您的邮箱，请妥善保管": "* Full key sent to your email, keep safe",
    "请确认所提供信息真实有效，并同意相关条款": "Confirm info is valid and agree to terms",
    "请填写以下信息申请设备授权密钥": "Fill in info to apply for device key",
    "请填写设备信息完成注册与授权": "Fill in device info to register",
    "输入设备编号和邮箱查询申请进度": "Enter device ID & email to check status",
    "设备编号为10-20位字母或数字": "Device ID: 10-20 alphanumeric chars",
    "设备唯一编号": "Device Unique ID",
    "请输入设备唯一编号": "Enter device unique ID",
    "请输入设备授权密钥": "Enter device auth key",
    "路由器用户名": "Router Username",
    "申请人姓名":   "Applicant Name",
    "请输入申请人姓名": "Enter applicant name",
    "姓名长度为2-20个字符": "Name: 2-20 characters",
    "联系邮箱":     "Email",
    "请输入联系邮箱": "Enter contact email",
    "请输入申请时填写的邮箱": "Enter application email",
    "申请时填写的邮箱": "App email",
    "请输入有效的邮箱地址": "Enter valid email address",
    "手机号码需以国家区号开头，例如中国为86，其他国家请参考国际区号": "Phone must start with country code (e.g., 86 for China)",
    "请说明申请密钥的原因和用途": "Explain reason and use for key",
    "请说明申请原因": "Explain reason",
    "请至少输入10个字符": "Min. 10 chars",
    "申请待审核":   "Pending Review",
    "申请审核中":   "Under Review",
    "申请已通过":   "Approved",
    "申请未通过":   "Rejected",
    "授权密钥：":   "Auth Key:",
    "拒绝原因：":   "Reject Reason:",
    "同意设备授权协议": "Agree to auth agreement",
    "智能模块全生命周期管理平台": "Smart Module Lifecycle Platform",
    "5G模块设备注册与授权管理": "5G Module Device Registration",
    "5G模块设备授权密钥申请": "5G Module Device Key Request",
    "管理模块": "Manage Mods",
    "已授权设备": "Auth Devices",
    "系统可用性": "System Uptime",
    "平均授权时间": "Avg Auth Time",
    "加密标准": "Encryption",
    "提交申请": "Submit",
    "审核验证": "Review",
    "密钥生成": "Key Gen",
    "完成": "Done",
    "管理员正在审核您的申请": "Admin reviewing appl.",
    "申请已提交，等待管理员审核": "Submitted, awaiting admin review",
    "申请已通过，密钥已发送至您的邮箱": "Approved, key sent to your email",
    "申请未通过，请查看拒绝原因": "Rejected, check rejection reason",
    "状态说明": "Status Info",
    "待审核": "Pending",
    "审核中": "Reviewing",
    "已通过": "Approved",
    "未通过": "Rejected",
    "查询您的设备密钥申请处理进度和结果": "Query device key application status",

    # AT commands descriptions
    "查询SIM卡状态 > AT+CPIN?":           "Query SIM status > AT+CPIN?",
    "查询模组IMEI > AT+CGSN":             "Query IMEI > AT+CGSN",
    "查询模组IMEI > AT+GSN":              "Query IMEI > AT+GSN",
    "查询模组IMEI > AT+EGMR=0,7":         "Query IMEI > AT+EGMR=0,7",
    "查询模组IMEI > AT+GTSN=0,7":         "Query IMEI > AT+GTSN=0,7",
    "查询模组IMEI > AT+LCTSN=0,7":        "Query IMEI > AT+LCTSN=0,7",
    "模组信息 > ATI":                      "Module info > ATI",
    "最小功能模式 > AT+CFUN=0":            "Minimal mode > AT+CFUN=0",
    "全功能模式 > AT+CFUN=1":              "Full mode > AT+CFUN=1",
    "重启模组 > AT+CFUN=1,1":             "Reboot > AT+CFUN=1,1",
    "重启模组 > AT+CFUN=15":              "Reboot > AT+CFUN=15",
    "重启模组 > AT+RESET":                "Reboot > AT+RESET",
    "查询PDP信息 > AT+CGDCONT?":          "Query PDP > AT+CGDCONT?",
    "查询PDP地址 > AT+CGPADDR":           "Query PDP addr > AT+CGPADDR",
    "查询网络信息 > AT+QNWINFO":          "Query net info > AT+QNWINFO",
    "查询网络信息 > AT+COPS?":            "Query operator > AT+COPS?",
    "查询网络信息 > AT^SYSINFOEX":        "Query net info > AT^SYSINFOEX",
    "查询网络及载波信息 > AT^DEBUG?":     "Query net & band > AT^DEBUG?",
    "查询载波聚合参数 > AT+QCAINFO":      "Query CA params > AT+QCAINFO",
    "查询载波聚合小区信息 > AT^CELLINFO=1": "Query CA cell info > AT^CELLINFO=1",
    "查询网络信号质量（4G） > AT+CSQ":    "Query signal (4G) > AT+CSQ",
    "查询网络信号质量（5G） > AT+CESQ":   "Query signal (5G) > AT+CESQ",
    "查询当前拨号模式 > AT+QCFG=":        "Query dial mode > AT+QCFG=",
    "查询当前拨号模式 > AT+SER?":         "Query dial mode > AT+SER?",
    "查询当前端口模式 > AT+GTUSBMODE?":   "Query port mode > AT+GTUSBMODE?",
    "获取模组温度 > AT+QTEMP":            "Get temp > AT+QTEMP",
    "获取模组温度 > AT^TEMP?":            "Get temp > AT^TEMP?",
    "获取模组温度 > AT+TEMP":             "Get temp > AT+TEMP",
    "查看当前电压 > AT+CBC":              "Check voltage > AT+CBC",
    "SIM卡状态上报 > AT^SIMSLOTURC=1":   "SIM slot URC > AT^SIMSLOTURC=1",
    "SIM卡状态上报 > AT+QSIMSTAT?":      "SIM status > AT+QSIMSTAT?",
    "获取SIM卡卡槽状态 > AT^SWITCH_SLOT?": "Get SIM slot > AT^SWITCH_SLOT?",
    "获取SIM卡卡槽状态 > AT^SIMSLOT?":   "Get SIM slot > AT^SIMSLOT?",
    "设置当前使用的为ESIM > at^switch_slot=1": "Set ESIM > at^switch_slot=1",
    "设置当前使用的为卡1 > at^switch_slot=0": "Set SIM1 > at^switch_slot=0",
    "设置当前使用的为卡1 > AT+GTDUALSIM=0": "Set SIM1 > AT+GTDUALSIM=0",
    "设置当前使用的为卡2 > AT+GTDUALSIM=1": "Set SIM2 > AT+GTDUALSIM=1",
    "设置当前使用的为卡1 > AT+QUIMSLOT=1": "Set SIM1 > AT+QUIMSLOT=1",
    "设置当前使用的为卡2 > AT+QUIMSLOT=2": "Set SIM2 > AT+QUIMSLOT=2",
    "设置当前使用的为卡1 > AT^SIMSLOT=1": "Set SIM1 > AT^SIMSLOT=1",
    "设置当前使用的为卡2 > AT^SIMSLOT=2": "Set SIM2 > AT^SIMSLOT=2",
    "ECM手动拨号 > AT+GTRNDIS=1,1":      "ECM dial > AT+GTRNDIS=1,1",
    "ECM拨号断开 > AT+GTRNDIS=0,1":      "ECM hang up > AT+GTRNDIS=0,1",
    "恢复自动搜索网络 > AT+GTACT=20":    "Auto net search > AT+GTACT=20",
    "报告一次当前BBIC的温度 > AT+MTSM=1,6": "Report BBIC temp > AT+MTSM=1,6",
    "报告一次当前射频的温度 > AT+MTSM=1,7": "Report RF temp > AT+MTSM=1,7",
    "QMI/GobiNet拨号模式 > AT+QCFG=":   "QMI/GobiNet mode > AT+QCFG=",
    "QMI/GobiNet拨号模式 > AT+GTUSBMODE=32": "QMI/GobiNet > AT+GTUSBMODE=32",
    "QMI/GobiNet拨号模式 > AT+SER=1,1": "QMI/GobiNet > AT+SER=1,1",
    "RNDIS拨号模式 > AT+GTUSBMODE=24":  "RNDIS mode > AT+GTUSBMODE=24",
    "RNDIS拨号模式 > AT+SER=3,1":       "RNDIS mode > AT+SER=3,1",
    "MBIM拨号模式 > AT+GTUSBMODE=30":   "MBIM mode > AT+GTUSBMODE=30",
    "MBIM拨号模式 > AT+SER=3,1":        "MBIM mode > AT+SER=3,1",
    "ECM拨号模式 > AT+GTUSBMODE=18":    "ECM mode > AT+GTUSBMODE=18",
    "NCM拨号模式 > AT+GTUSBMODE=18":    "NCM mode > AT+GTUSBMODE=18",
    "ECM拨号模式 > AT+SER=2,1":         "ECM mode > AT+SER=2,1",
    "NCM拨号模式 > AT+SER=2,1":         "NCM mode > AT+SER=2,1",
    "Ping地址【网络狗】": "Ping Addr [NetDog]",
    "是否开启【网络狗】": "Enable [NetDog]",

    # UE state strings
    "UE 正在搜索但未找到合适的 3G/4G/5G 小区": "UE searching, no suitable cell found",
    "UE 正在驻留一个小区且已注册到网络，处于空闲模式": "UE camped & registered, idle mode",
    "UE 正在驻留一个小区但未注册到网络": "UE camped, not registered",
    "UE 正在驻留一个小区且已注册到网络": "UE camped and registered",

    # APN info
    "移动APN：CMNET：适用于大多数应用场景,CMWAP：适用于轻量级浏览和邮件收发":
        "Mobile APN: CMNET(general), CMWAP(light browsing)",
    "联通APN：UNINET：兼容性优先的通用选择,WONET：5G专属优化的低延迟方案,CUIOT：高峰时段的QoS优先级提升,3GNET与WONET组合：弱信号区域的补救措施":
        "Unicom APN: UNINET(compat), WONET(5G), CUIOT(QoS), 3GNET+WONET(weak signal)",
    "电信APN：CTLET:电信5G网络可以实现较快的网速,CTNET：速度相对较快,CTWAP：通常速度较慢":
        "Telecom APN: CTLET(5G fast), CTNET(fast), CTWAP(slow)",
    "自动APN开启时，系统将根据SIM卡信息自动配置接入点名称，无需手动输入。如遇连接问题，可尝试关闭自动APN并手动设置正确的APN。":
        "Auto APN configures access point from SIM info. If issues arise, disable auto APN and set manually.",
    "自动串口管理开启时，系统将根据设备连接状态自动选择串口，无需手动指定。如遇通信问题，可尝试关闭自动串口管理并手动选择正确的串口。":
        "Auto serial management selects port by device state. If issues arise, disable and select manually.",
    " 请连接串口设备并刷新设备列表，以便使用AT命令管理功能 ":
        " Connect serial device and refresh to use AT commands ",
    " 注意：修改硬件设置将导致路由器重启以应用配置，重启过程中可能会短暂断网。 ":
        " Note: Modifying HW settings will reboot the router to apply changes. ",

    # Push platform descriptions
    "公众号。": "WeChat Pub.",
    "企业微信支持应用内消息和机器人消息两种模式。配置说明：<a href=":
        "WeCom supports in-app and bot messages. Docs: <a href=",

    # Misc input placeholders
    "请输入APN":       "Enter APN",
    "输入手机号码":    "Enter phone number",
    "输入消息内容...": "Enter message...",
    "搜索消息...":     "Search SMS...",
    "搜索日志...":     "Search logs...",
    "搜索基站ID或位置...": "Search cell/loc",
    "搜索频段名称或编号...": "Search band name or number...",
    "检索命令或描述...": "Search commands...",
    "输入AT命令 (例如: AT+CSQ)": "Enter AT command (e.g.: AT+CSQ)",
    "点击命令可直接选中": "Click command to select",
    "等待设备响应...":  "Waiting resp...",
    "正则表达式:":      "Regex:",
    "关键词":           "Keywords",
    "收件人":           "Recipient",
    "消息内容":         "Message",
    "消息详情":         "Msg Details",
    "短信内容:":        "SMS Content:",
    "常用命令:":        "Common Cmds:",

    # Location data (used as demo data probably)
    "北京市": "Beijing",
    "上海市": "Shanghai",
    "广州市": "Guangzhou",
    "深圳市": "Shenzhen",
    "杭州市": "Hangzhou",
    "南京市": "Nanjing",
    "成都市": "Chengdu",
    "武汉市": "Wuhan",
    "朝阳区": "Chaoyang",
    "海淀区": "Haidian",
    "静安区": "Jing'an",
    "浦东区": "Pudong",
    "天河区": "Tianhe",
    "南山区": "Nanshan",
    "西湖区": "Xihu",
    "玄武区": "Xuanwu",
    "中关村": "Zhongcun",
    "学院路": "Xueyuan",
    "南京路": "Nanjing R",
    "科技园": "Tech Park",
    "金融街": "Finance R",
    "大学城": "Univ. Ct.",
    "工业区": "Ind Zone",
    "商业区": "Biz Zone",

    # Time
    "昨天": "Yest.",
    "周日": "Sun",
    "周一": "Mon",
    "周二": "Tue",
    "周三": "Wed",
    "周四": "Thu",
    "周五": "Fri",
    "周六": "Sat",
    "新消息": "New SMS",
    "收件箱": "Inbox",
    "发件箱": "Outbox",
    "已读":   "Read",
    "未读":   "Unread",

    # Misc short labels that appear as standalone strings
    "用户选择了串口: ": "Serial sel: ",
    "发送: ":           "TX: ",
    "响应: ":           "RX: ",
    "匹配成功":         "Match OK",
    "匹配失败":         "Match FAIL",
    " 匹配的命令":      " matches",
    "已选择设备: ":     "Selected device: ",
    "回复 ":            "Reply: ",
}


def pad_to_length(s: str, target_bytes: int) -> bytes:
    """Encode s as UTF-8 and pad with spaces to exactly target_bytes."""
    encoded = s.encode("utf-8")
    if len(encoded) > target_bytes:
        raise ValueError(
            f"Translation '{s}' ({len(encoded)}B) exceeds original ({target_bytes}B)"
        )
    return encoded + b" " * (target_bytes - len(encoded))


def patch(input_path: str, output_path: str):
    with open(input_path, "rb") as f:
        data = bytearray(f.read())

    total = 0
    skipped = []

    for zh, en in TRANSLATIONS.items():
        zh_bytes = zh.encode("utf-8")
        try:
            replacement = pad_to_length(en, len(zh_bytes))
        except ValueError as e:
            skipped.append(str(e))
            continue

        count = 0
        start = 0
        while True:
            pos = data.find(zh_bytes, start)
            if pos == -1:
                break
            data[pos : pos + len(zh_bytes)] = replacement
            start = pos + len(zh_bytes)
            count += 1

        if count:
            total += count
            print(f"  [{count:3d}x] \"{zh}\" → \"{en}\"")

    print(f"\nTotal replacements: {total}")
    if skipped:
        print(f"\nSkipped (translation too long):")
        for s in skipped:
            print(f"  {s}")

    with open(output_path, "wb") as f:
        f.write(data)

    # Copy execute permissions from original
    orig_mode = os.stat(input_path).st_mode
    os.chmod(output_path, orig_mode)
    print(f"\nPatched binary written to: {output_path}")
    print(f"Size: {len(data):,} bytes")


if __name__ == "__main__":
    src = os.path.join(os.path.dirname(__file__), "modemserver")
    dst = os.path.join(os.path.dirname(__file__), "modemserver_en")
    if not os.path.exists(src):
        print(f"Error: {src} not found")
        sys.exit(1)
    print(f"Patching: {src}\n")
    patch(src, dst)
